algoritmo "semnome"
var
          C,F3, F1,F2 :inteiro
inicio

      F1<- 0
      Escreva (F1)
      F2<- 1
      Escreva (F2)
      
     Para C<- 3 ate 15 faca
       F3 <- F1+ F2
       Escreva (F3)
       F1 <- F2
       F2 <- F3
     FimPara
      
      
   //F1 A + F2B = F3C  escreve o (F3 = (1))
   //F1 A  F2 B
   // F2 B = F3 C  igual a soma (F1+F2)
   // B + C = D
   // B = C
   // C = D
   // C + D = F






fimalgoritmo
     
     
     
     

     

fimalgoritmo